version: '3'
volumes:
  postgres_data: {}

services:

  nginx:
    image: bubelov/nginx-alpine-geoip2
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/logs:/var/log/nginx
    # environment:
    #   - VIRTUAL_HOST=m4rr.ru
    #   - LETSENCRYPT_HOST=m4rr.ru
    #   - LETSENCRYPT_EMAIL=remarr@m4rr.ru
    depends_on:
      - app

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
