version: '3'
services:
  nginx:
    # image: nginx
    build: ./docker/web/
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /srv/volumes/nginx/html:/usr/share/nginx/html
      - /srv/volumes/nginx/certs:/etc/nginx/certs:ro
  # nginx-gen:
  #   image: jwilder/docker-gen
  #   command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  #   container_name: nginx-gen
  #   restart: always
  #   volumes:
  #     - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
  #     - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
  #     - /srv/volumes/nginx/html:/usr/share/nginx/html
  #     - /srv/volumes/nginx/certs:/etc/nginx/certs:ro
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  # nginx-letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: nginx-letsencrypt
  #   restart: always
  #   volumes:
  #     - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
  #     - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
  #     - /srv/volumes/nginx/html:/usr/share/nginx/html
  #     - /srv/volumes/nginx/certs:/etc/nginx/certs:rw
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     NGINX_DOCKER_GEN_CONTAINER: nginx-gen
  #     NGINX_PROXY_CONTAINER: nginx-web
  db:
    image: postgres
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
  app:
    # image: my_genius_app
    command: bundle exec unicorn -p 3000
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 3000:80
    environment: &environment
      - SQUIRTUAL_HOST=m4rr.ru
      # - VIRTUAL_HOST=m4rr.ru
      # - LETSENCRYPT_HOST=m4rr.ru
      # - LETSENCRYPT_EMAIL=remarr@m4rr.ru
    volumes: &volumes
      - ./volumes/app/log:/app/log
      - ./volumes/app/tmp:/app/tmp
networks:
  default:
    external:
      name: webproxy
