# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d76ee8f8ee09e35ccbc1c2676f27a70a93c5df350c462278bde520266b4f3380a8dc60e8f4dfbb5527afd4aff08ab73eb79df61181760fb4cdee2feed889a36

test:
  secret_key_base: d6de14662c9d81b790095043956f070afdd59316e99c3591dbb092134dc4d6130581b245524c598bae6876ee207fa41b3a7ab06714ffe76ffc3dd7d8b083f4bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:
  d6de14662c9d81b7qcs90f070afdd59316e99c3591dbb092134dc4d613058f1b245524c598bae6876ee207fa41b3a7ab06714ffe76ffc3dd7d8b09817ryuefdb
  # <%= ENV["SECRET_KEY_BASE"] %>

